import "./globals.css";
import KakaoChatButton from "@/components/KakaoChatButton";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="ko">
        <body>
        {children}
        <KakaoChatButton/>
        </body>
        </html>
    );
}
