import "./globals.css";
import KakaoChatButton from "@/components/share/KakaoChatButton";
import Navbar from "@/components/share/Navbar";
import Footer from "@/components/share/Footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/logo/favicon.svg"
    }
};

export default function RootLayout({children}) {
    return (
        <html lang="ko">
        <body>
        <Navbar/>
        {children}
        <KakaoChatButton/>
        <Footer/>
        </body>
        </html>
    );
}
